package com.springspartans.shopkart.repository;

import com.springspartans.shopkart.model.Customer;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.jdbc.Sql;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect"
})
@Sql(statements = {
        "CREATE TABLE IF NOT EXISTS customer (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(50) NOT NULL, " +
                "email VARCHAR(50) NOT NULL UNIQUE, " +
                "password VARCHAR(72) NOT NULL, " +
                "address VARCHAR(255) NOT NULL, " +
                "phone BIGINT NOT NULL, " +
                "profile_pic VARCHAR(50), " +
                "signup_date TIMESTAMP, " +
                "last_login_date TIMESTAMP" +
        ")"
})
class CustomerRepositoryTest {

    @Autowired
    private CustomerRepository customerRepository;

    @Test
    void shouldFindCustomerByEmail() {
        // Arrange
        Customer customer = new Customer();
        customer.setName("Juan Perez");
        customer.setEmail("juan@gmail.com");
        customer.setPassword("123456");
        customer.setAddress("Arequipa");
        customer.setPhone(987654321L);
        customer.setProfilePic("perfil.jpg");

        customerRepository.saveAndFlush(customer);

        // Act
        Optional<Customer> result = customerRepository.findByEmail("juan@gmail.com");

        // Assert
        assertTrue(result.isPresent());
        assertEquals("Juan Perez", result.get().getName());
        assertEquals("juan@gmail.com", result.get().getEmail());
    }

    @Test
    void shouldCountCustomersBySignupDateBetween() {
        // Arrange
        Timestamp signupDate = Timestamp.from(Instant.now());

        Customer customer = new Customer();
        customer.setName("Maria Lopez");
        customer.setEmail("maria@gmail.com");
        customer.setPassword("abcdef");
        customer.setAddress("Lima");
        customer.setPhone(912345678L);
        customer.setSignup_date(signupDate);

        customerRepository.saveAndFlush(customer);

        Timestamp startDate = Timestamp.from(Instant.now().minusSeconds(3600));
        Timestamp endDate = Timestamp.from(Instant.now().plusSeconds(3600));

        // Act
        int total = customerRepository.countBySignup_dateBetween(startDate, endDate);

        // Assert
        assertEquals(1, total);
    }

    @Test
    void shouldCountCustomersByLastLoginDateBetween() {
        // Arrange
        Timestamp signupDate = Timestamp.from(Instant.now());
        Timestamp lastLoginDate = Timestamp.from(Instant.now());

        Customer customer = new Customer();
        customer.setName("Carlos Ramos");
        customer.setEmail("carlos@gmail.com");
        customer.setPassword("123abc");
        customer.setAddress("Cusco");
        customer.setPhone(923456789L);
        customer.setSignup_date(signupDate);
        customer.setLast_login_date(lastLoginDate);

        customerRepository.saveAndFlush(customer);

        Timestamp startDate = Timestamp.from(Instant.now().minusSeconds(3600));
        Timestamp endDate = Timestamp.from(Instant.now().plusSeconds(3600));

        // Act
        int total = customerRepository.countByLast_login_dateBetween(startDate, endDate);

        // Assert
        assertEquals(1, total);
    }
}